import type { Metadata } from "next";

// styles
import "@/styles/global.scss";

// recoil
import RecoilRootProvider from "@/lib/recoil/recoilRootProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RecoilRootProvider>{children}</RecoilRootProvider>
      </body>
    </html>
  );
}
